name: Update JSON
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
      - name: Create local changes
        run: |
          pip3 install -r scraper/requirements.txt
          python3 scraper/src/meta.py
          python3 scraper/src/pmu.py
          python3 scraper/src/donors.py
          python3 scraper/src/hospitals.py
          python3 scraper/src/associate.py
          python3 scraper/src/status.py
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --staged --quiet || git commit -am "🌍 Update JSON - $(date -d '+5 hours +30 minutes' +'%d %b %Y | %I:%M %p')"
          git push
